### ISSUE TITLE
White bar above the Brand Bar when vertical scroll bar is present

### ISSUE THREAD

**Issue by v-chloc** [OfficeDev/Excel-Add-in-JavaScript-SalesTracker#3]
Either adjust the height of the task pane until a scroll bar appears or set the screen resolution to 1366 x 768, which at full screen should show a scroll bar. There seems to be an invisible element right above the Brand Bar that spans the width of the task pane.

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
