### ISSUE TITLE
Error While Running this project

### ISSUE THREAD

**Issue by abhishekhgit** [OfficeDev/Excel-Add-in-JavaScript-SalesTracker#7]
Unhandled exception at line 7, column 7910 in https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/js/fabric.min.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'pickadate'

**Comment by Rick-Kirkham** [comment]
@abhishekhgit Did you follow the steps in the section "**Get the PickADate library**" of the readme?

**Comment by davidchesnut** [comment]
Closing all issues since this repo is being archived and no longer maintained.
